import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const urls = [
  { name: "Inicio", url: "/" },
  { name: "Servicios", url: "/servicios" },
  { name: "Nosotros", url: "/nosotros" },
  { name: "Contacto", url: "/contacto" },
  { name: "Galería", url: "/galeria" },
];

export const socials = [
  { name: "Facebook", url: "https://www.facebook.com", svg:'/svg/facebook.svg'},
  { name: "Instagram", url: "https://www.instagram.com", svg:'/svg/instagram.svg'},
  { name: "WhatsApp", url: "https://wa.me/+573143826540", svg:'/svg/whatsapp.svg'},
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav links={urls} socials={socials}/>
        {children}
        </body>
    </html>
  );
}
