import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Banner from "@/components/Banner";
import BackTopButton from "@/components/BackTopButton";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const urls = [
  { name: "Inicio", url: "/" },
  { name: "Servicios", url: "/servicios/" },
  { name: "Nosotros", url: "/nosotros/" },
  { name: "Galería", url: "/galeria/" },
  { name: "Contacto", url: "/contacto/" },
];

export const socials = [
  { name: "Facebook", url: "https://www.facebook.com/operadoracanaimatours", svg:'/svg/facebook.svg'},
  { name: "Instagram", url: "https://www.instagram.com/canaimatours1/", svg:'/svg/instagram.svg'},
  { name: "WhatsApp", url: "https://wa.me/+573143826540", svg:'/svg/whatsapp.svg'},
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav links={urls} socials={socials}/>
        <Banner/>
        {children}
        <BackTopButton/>
        <Footer links={urls} socials={socials}/>
        </body>
    </html>
  );
}
